//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewOrderDB
    {
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductCategory { get; set; }
        public int ProductQuantity { get; set; }
        public string ProductSize { get; set; }
        public int ProductPrice { get; set; }
        public int CustomerID { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<int> TotalCost { get; set; }
    }
}
